### ISSUE TITLE
[Enhancement] Create a install script

### ISSUE THREAD

**Issue by Khhs167** [MCPI-Revival/MCPIL#11]
This is a great thing, but kind of hard to install, so what about a .sh that installs mcpi-docker and mcpil-r, to ease the process.

**Comment by mobilegmYT** [comment]
I wouldn't exactly call it hard to copy and paste 2 commands. Even if we made a install script, it would be even longer. Both mcpil-r and mcpi-docker and planed to be integrated into one install script in pi-apps.

**Comment by Alvarito050506** [comment]
Hello! Yes, we're aware that it might me a bit difficult to install, but it's mainly not the fault of the main devs, since currently RPiOS is based on Debian Buster, and Docker requires newer packages only avaiable in Bullseye or via the backports. Most of the installation steps that feel like it's "extra" stuff is in fact adding the `buster-backports` repository and getting the latest Docker version.

**Comment by TheBrokenRail** [comment]
This has been added to Pi-Apps.
